INSERT INTO tweets (user_id, content, media) 
VALUES 
(5, 'My sister is so embarrassing, and I want to dream bigger. For all funky fluff, in the end. #cheapbling #randomtweet', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/1.jpg'),
(4, 'My smile is fantastic, and I want to go to Mars. Here is to more cowards, strictly speaking. #sometrain #randomtweet', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/2.jpg'),
(2, 'hi, grandma? can u come pick me up from my rap battle? its over. no, i lost. he saw u drop me off &amp; did a pretty devastating rhyme about it', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/3.jpg'),
(5, 'The owner of my AirBnB has a dog named Kevin. His human-sounding name terrified me at first.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/4.jpg'),
(2, 'MY DENTIST ASKED HIS ASSISTANT TO SUCTION (HE WATER OUT OF MY MOUTH)BUT I THOUGHT HE WAS TALKING TO ME SO I SUCKED HIS FINGER. IM MORTIFIED', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/5.jpg'),
(4, 'I like it when they put "the end" after a movie, so that you know not to stay sat in your seat for the rest of your life.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/6.jpg'),
(3, 'Lord give me the commitment of a guy they forced into a polar bear costume going full method during an escape drill ', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/7.jpg'),
(2, 'FIRST PERSON TO GET A CAT: haha this thing is an asshole I’m gonna keep it', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/8.jpg'),
(4, 'Social best research wish particularly customer fine.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/9.jpg'),
(5, 'Rich the land nothing everything safe not.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/10.jpg'),
(1, 'Back sing door season want west group.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/11.jpg'),
(2, 'Know own specific good.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/12.jpg'),
(3, 'Test ok individual compare pass.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/13.jpg'),
(6, 'Series Mrs administration decision.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/14.jpg'),
(5, 'Each window major live time experience.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/15.jpg'),
(3, 'Response live nor right simple main head.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/16.jpg'),
(5, 'My employee simple week.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/17.jpg'),
(3, 'Your end letter.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/18.jpg'),
(2, 'Shoulder your our international.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/19.jpg'),
(3, 'Fill wind above goal.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/20.jpg'),
(4, 'Benefit race law enjoy during suffer design.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/21.jpg'),
(6, 'My expert product fish.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/22.jpg'),
(2, 'Rise build guy lead.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/23.jpg'),
(1, 'Themselves central side increase million citizen.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/24.jpg'),
(4, 'School factor ago any wind.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/25.jpg'),
(5, 'Walk culture fear east political.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/26.jpg'),
(3, 'Answer a mission worker.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/27.jpg'),
(3, 'Series leg always law behavior citizen form.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/28.jpg'),
(1, 'Nearly require training second throughout many.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/29.jpg'),
(3, 'Political cultural point able leader almost few person.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/30.jpg'),
(4, 'Marriage name because agency election.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/31.jpg'),
(1, 'Herself large performance enough must drop raise.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/32.jpg'),
(5, 'Avoid attack road blood.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/33.jpg'),
(5, 'Author life maintain lose perhaps late.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/34.jpg'),
(5, 'Moment southern capital Democrat tend.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/35.jpg'),
(3, 'Simply feeling community brother tonight pick.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/36.jpg'),
(2, 'Beat employee particular behavior room fish course.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/37.jpg'),
(2, 'Bring they Mr read.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/38.jpg'),
(6, 'Suddenly data party throughout do.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/39.jpg'),
(5, 'Behavior very reality a especially movie address.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/40.jpg'),
(6, 'Teach throughout full though voice share.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/41.jpg'),
(6, 'Share whether themselves sometimes research.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/42.jpg'),
(2, 'Special along gun society.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/43.jpg'),
(2, 'Per end color president.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/44.jpg'),
(6, 'Send major positive year do successful war five.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/45.jpg'),
(5, 'Avoid ready tend capital but seat.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/46.jpg'),
(4, 'Like feeling if side.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/47.jpg'),
(5, 'Last notice meet many view film.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/48.jpg'),
(3, 'Best front hot talk history stop.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/49.jpg'),
(6, 'Defense population evening position dinner method.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/50.jpg'),
(6, 'Interest south site election scientist star church.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/51.jpg'),
(4, 'Big country food security.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/52.jpg'),
(1, 'Its every network check probably.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/53.jpg'),
(1, 'Operation list pick result.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/54.jpg'),
(1, 'Join use several spend.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/55.jpg'),
(1, 'Site gun provide American she.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/56.jpg'),
(5, 'Condition federal executive.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/57.jpg'),
(4, 'About mind ahead western president.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/58.jpg'),
(5, 'Citizen wait young help affect until.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/59.jpg'),
(5, 'Education management state sing box area.', 'https://pikagram-pics1.s3.us-east-2.amazonaws.com/60.jpg')